export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const  SET_CART_ITEMS ='SET_CART_ITEMS';
export const  CART_UPDATE_ITEM ='CART_UPDATE_ITEM';

export const CART_ADD_ITEM2 = 'CART_ADD_ITEM2';
export const CART_REMOVE_ITEM2 = 'CART_REMOVE_ITEM2';